Fix setuptools build error due to flat project layout
>  error: Multiple top-level packages discovered in a flat-layout: ['wagtailcaptcha', 'coverage_html_report'].